[package]
name = "marisa-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
lazy_static = "1.4.0"
egui = "0.20.0"
egui_winit_vulkano = "0.21.0"
vulkano = "0.32.3"
